pipeline{
  agent any
  stages {
    stage('Build'){
      steps {
        build 'PES2UG21CS547-1'
        sh 'gcc main/main.cpp -o output'
      }
    }
    stage('Test'){
      steps {
        sh './output'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploy'
      }
    }
  }
  post {
    failure {
      echo 'Pipeline failed'
    }
  }
}
